#
# The module Util
#

ROOT_DIR := ..
include $(ROOT_DIR)/Makefile.def

TYPE := lib
NAME := util
DEPS :=
DEFS +=
SRCS := \
	ini.c \
	timer.cpp
SRCS_DIRS :=
LIBS += -lrt

include $(ROOT_DIR)/Makefile.rules
