#
# The module Start client
#

ROOT_DIR := ../..
include $(ROOT_DIR)/Makefile.def

TYPE := shared_lib
NAME := mysqludf_source
DEPS :=
DEPS_DIRS := 
DEFS +=
SRCS := mysqludf_source.cpp
SRC_DIRS :=
LIBS += -lmysqlclient

include $(ROOT_DIR)/Makefile.rules
