#
# The module Db
#

ROOT_DIR := ..
include $(ROOT_DIR)/Makefile.def

TYPE := lib
NAME := db
DEPS :=
DEPS_DIRS :=
DEFS +=
SRCS := \
	ASEMP.cpp \
	Actions.cpp \
	AlarmSystem.cpp \
	AlarmsRetrosave.cpp \
	Bypass.cpp \
	Commands.cpp \
	Database.cpp \
	DeviceRegistration.cpp \
	Diagnostics.cpp \
	HVAC.cpp \
	Humidifier.cpp \
	PendingAction.cpp \
	Relays.cpp \
	RemoteControl.cpp \
	Sensorsdyn.cpp \
	Settings.cpp \
	SmartDevices.cpp \
	SmartPlugdyn.cpp \
	SmartSensor.cpp \
	SmartSensorRaw.cpp \
	Thermostat.cpp \
	ZedDev.cpp \
	Zigbee.cpp \
	ZigbeeASE.cpp \
	ZigbeeAlarm.cpp \
	ZigbeeCommands.cpp \
	ZigbeeDevice.cpp \
	ZigbeeHA.cpp \
	Zone.cpp
	
SRC_DIRS := 
LIBS += 

include $(ROOT_DIR)/Makefile.rules
