#!/bin/bash

echo "Installing..."
cp ../etc/liblog4cplus.a  	 /usr/local/lib
cp ../etc/liblog4cplus-1.1.so.9.0.1  /usr/local/lib
sed -i '$ a\\/usr\/local\/lib' 	 /etc/ld.so.conf
ldconfig
echo "Succsessful..."

