#
# The module Zigbee (synchronous part only)
#

ROOT_DIR := ..
include $(ROOT_DIR)/Makefile.def

TYPE := lib
NAME := zigbee_sync
DEPS := 
DEFS += 
#-DSIM
SRCS := zigbee_sync.cpp
SRCS_DIRS :=
LIBS +=

include $(ROOT_DIR)/Makefile.rules
